version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: dynamics-web-api
    versions:
    - 1.7.0
    - 1.7.1
    - 1.7.2
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: "@wdio/local-runner"
    versions:
    - 6.12.1
  - dependency-name: "@wdio/junit-reporter"
    versions:
    - 6.11.0
  - dependency-name: "@wdio/spec-reporter"
    versions:
    - 6.11.0
